name: Build Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build Application
        run: mvn clean package

      - name: Upload WAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrainBook
          path: target/*.war
