name: Upload to Nexus

on:
  workflow_run:
    workflows:
      - SonarQube Analysis
    types:
      - completed

jobs:
  nexus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Maven Settings
        run: |
          mkdir -p ~/.m2

          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>nexus</id>
                <username>${{ secrets.NEXUS_USERNAME }}</username>
                <password>${{ secrets.NEXUS_PASSWORD }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Deploy Artifact to Nexus
        run: |
          mvn clean deploy \
          -DaltDeploymentRepository=nexus::default::http://${{ secrets.NEXUS_HOST }}:8081/repository/maven-releases/
