name: Deploy to Tomcat

on:
  workflow_run:
    workflows: ["Upload to Nexus"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build WAR File
        run: mvn clean package

      - name: Deploy WAR to Tomcat
        run: |
          WAR_FILE=$(find target -name "*.war" | head -n 1)

          curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
          -T "$WAR_FILE" \
          "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/TrainBook=true"
